#!/usr/bin/env bash

# Runs during git flow hotfix finish and a tag message is given
#
# Positional arguments:
# $1 Message
# $2 Full version
#
# Return MESSAGE
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop

SCRIPT_PATH="$0"
MESSAGE="$1"
VERSION="$2"

# Implement your script here.

node "$(dirname "$SCRIPT_PATH")"/git-tag-message-formatter.js "$MESSAGE" "$VERSION"

exit 0
